---
services:
  wireguard-kernel-modules:
    command: sleep infinity
    container_name: wireguard-kernel-modules
    environment:
      - KERNEL_DSM_VERSION=${KERNEL_DSM_VERSION}
      - KERNEL_VERSION=${KERNEL_VERSION}
      - PACKAGE_NAME=${PACKAGE_NAME}
      - PACKAGE_VERSION=${PACKAGE_VERSION}
      - TAR_CMD="fakeroot tar"
      - WORKSPACE=${WORKSPACE}
    image: ghcr.io/synocommunity/spksrc
    init: true
    platform: linux/amd64
    privileged: true
    volumes:
      - ..:${WORKSPACE}:cached
      - ../spksrc:/spksrc:cached
    working_dir: /spksrc
