---
services:
  wireguard-kernel-modules:
    command: sleep infinity
    container_name: wireguard-kernel-modules
    environment:
      - KERNEL_DSM_VERSION=${KERNEL_DSM_VERSION}
      - KERNEL_VERSION=${KERNEL_VERSION}
      - PACKAGE_NAME=${PACKAGE_NAME}
      - PACKAGE_VERSION=${PACKAGE_VERSION}
      - WORKSPACE=${WORKSPACE}
    image: "mcr.microsoft.com/devcontainers/base:1-${VARIANT}"
    init: true
    volumes:
      - ..:${WORKSPACE}:cached
