#!/bin/sh
# scripts/start-stop-status

IPTABLES_MODULE_LIST="/usr/syno/etc/iptables_modules_list"
MODULES=("KERNEL_MODULES")
SERVICE="PACKAGE_NAME"
SYNOMODULETOOL="/usr/syno/bin/synomoduletool"

case $1 in
    start)
        # source "$IPTABLES_MODULE_LIST"

        # if [ -x "$SYNOMODULETOOL" -a -f "$IPTABLES_MODULE_LIST" ]; then
        #     sysctl -w net.ipv4.ip_forward=1
        #     "$SYNOMODULETOOL" --insmod "$SERVICE" $KERNEL_MODULES_CORE
        #     echo "Loaded $? iptables core modules"

        #     "$SYNOMODULETOOL" --insmod "$SERVICE" $KERNEL_MODULES_NAT
        #     echo "Loaded $? iptables NAT modules"
        # fi

        # for module in "${MODULES[@]}"; do
        #     echo "Inserting module $module"
        #     insmod $module $SYNOPKG_PKGDEST/wireguardkernelmodules/${module}.ko
        #     echo "Result of insmod $module $SYNOPKG_PKGDEST/wireguardkernelmodules/${module}.ko: $?"
        # done

        echo "Hello World" > $SYNOPKG_TEMP_LOGFILE
        exit 0
    ;;
    stop)
        # source "$IPTABLES_MODULE_LIST"

        # for module in "${MODULES[@]}"; do
        #     echo "Removing module $module"
        #     rmmod -f $SYNOPKG_PKGDEST/wireguardkernelmodules/${module}.ko
        #     echo "Result of rmmod -f $module: $?"
        # done

        # if [ -x "$SYNOMODULETOOL" -a -f "$IPTABLES_MODULE_LIST" ]; then
        #     "$SYNOMODULETOOL" --rmmod "$SERVICE" $KERNEL_MODULES_NAT
        #     "$SYNOMODULETOOL" --rmmod "$SERVICE" $KERNEL_MODULES_CORE
        # fi

        echo "Goodbye World" > $SYNOPKG_TEMP_LOGFILE
        exit 0
    ;;
    status)
        exit 0
    ;;
esac
