#!/bin/bash
# SynoBuildConf/build

case ${MakeClean} in
    [Yy][Ee][Ss])
        make distclean
    ;;
esac

case ${CleanOnly} in
    [Yy][Ee][Ss])
        make clean
    ;;
esac

make ${MAKE_FLAGS}
